package com.funtalk.pojo.rightmanage;

/**
 * FuncTypeId generated by MyEclipse Persistence Tools
 */

public class FuncTypeId implements java.io.Serializable {

	// Fields

	private Long functypeid;

	private String functypename;

	// Constructors

	/** default constructor */
	public FuncTypeId() {
	}

	/** full constructor */
	public FuncTypeId(Long functypeid, String functypename) {
		this.functypeid = functypeid;
		this.functypename = functypename;
	}

	// Property accessors

	public Long getFunctypeid() {
		return this.functypeid;
	}

	public void setFunctypeid(Long functypeid) {
		this.functypeid = functypeid;
	}

	public String getFunctypename() {
		return this.functypename;
	}

	public void setFunctypename(String functypename) {
		this.functypename = functypename;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuncTypeId))
			return false;
		FuncTypeId castOther = (FuncTypeId) other;

		return ((this.getFunctypeid() == castOther.getFunctypeid()) || (this
				.getFunctypeid() != null
				&& castOther.getFunctypeid() != null && this.getFunctypeid()
				.equals(castOther.getFunctypeid())))
				&& ((this.getFunctypename() == castOther.getFunctypename()) || (this
						.getFunctypename() != null
						&& castOther.getFunctypename() != null && this
						.getFunctypename().equals(castOther.getFunctypename())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFunctypeid() == null ? 0 : this.getFunctypeid()
						.hashCode());
		result = 37
				* result
				+ (getFunctypename() == null ? 0 : this.getFunctypename()
						.hashCode());
		return result;
	}

}