package com.funtalk.pojo.rightmanage;

/**
 * FuncButton generated by MyEclipse Persistence Tools
 */

public class FuncButton implements java.io.Serializable {

	// Fields

	private FuncButtonId id;

	// Constructors

	/** default constructor */
	public FuncButton() {
	}

	/** full constructor */
	public FuncButton(FuncButtonId id) {
		this.id = id;
	}

	// Property accessors

	public FuncButtonId getId() {
		return this.id;
	}

	public void setId(FuncButtonId id) {
		this.id = id;
	}

}