package com.funtalk.pojo.rightmanage;

/**
 * FuncType generated by MyEclipse Persistence Tools
 */

public class FuncType implements java.io.Serializable {

	// Fields

	private FuncTypeId id;

	// Constructors

	/** default constructor */
	public FuncType() {
	}

	/** full constructor */
	public FuncType(FuncTypeId id) {
		this.id = id;
	}

	// Property accessors

	public FuncTypeId getId() {
		return this.id;
	}

	public void setId(FuncTypeId id) {
		this.id = id;
	}

}