package com.funtalk.pojo.rightmanage;

import java.util.Date;

/**
 * Log generated by MyEclipse Persistence Tools
 */

public class Log implements java.io.Serializable {

	// Fields

	private Long seq;

	private String username;

	private Date operateTime;

	private String operateType;

	private String operateSrc;

	private String operateDest;

	private String memo;

	// Constructors

	/** default constructor */
	public Log() {
	}

	/** minimal constructor */
	public Log(Long seq, Date operateTime, String operateType,
			String operateSrc, String operateDest) {
		this.seq = seq;
		this.operateTime = operateTime;
		this.operateType = operateType;
		this.operateSrc = operateSrc;
		this.operateDest = operateDest;
	}

	/** full constructor */
	public Log(Long seq, String username, Date operateTime,
			String operateType, String operateSrc, String operateDest,
			String memo) {
		this.seq = seq;
		this.username = username;
		this.operateTime = operateTime;
		this.operateType = operateType;
		this.operateSrc = operateSrc;
		this.operateDest = operateDest;
		this.memo = memo;
	}

	// Property accessors

	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getOperateType() {
		return this.operateType;
	}

	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	public String getOperateSrc() {
		return this.operateSrc;
	}

	public void setOperateSrc(String operateSrc) {
		this.operateSrc = operateSrc;
	}

	public String getOperateDest() {
		return this.operateDest;
	}

	public void setOperateDest(String operateDest) {
		this.operateDest = operateDest;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}