package com.funtalk.pojo.rightmanage;

/**
 * RoleLevelId generated by MyEclipse Persistence Tools
 */

public class RoleLevelId implements java.io.Serializable {

	// Fields

	private Long PRoleid;

	private Long roleid;

	// Constructors

	/** default constructor */
	public RoleLevelId() {
	}

	/** full constructor */
	public RoleLevelId(Long PRoleid, Long roleid) {
		this.PRoleid = PRoleid;
		this.roleid = roleid;
	}

	// Property accessors

	public Long getPRoleid() {
		return this.PRoleid;
	}

	public void setPRoleid(Long PRoleid) {
		this.PRoleid = PRoleid;
	}

	public Long getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Long roleid) {
		this.roleid = roleid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleLevelId))
			return false;
		RoleLevelId castOther = (RoleLevelId) other;

		return ((this.getPRoleid() == castOther.getPRoleid()) || (this
				.getPRoleid() != null
				&& castOther.getPRoleid() != null && this.getPRoleid().equals(
				castOther.getPRoleid())))
				&& ((this.getRoleid() == castOther.getRoleid()) || (this
						.getRoleid() != null
						&& castOther.getRoleid() != null && this.getRoleid()
						.equals(castOther.getRoleid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPRoleid() == null ? 0 : this.getPRoleid().hashCode());
		result = 37 * result
				+ (getRoleid() == null ? 0 : this.getRoleid().hashCode());
		return result;
	}

}