package com.funtalk.pojo.rightmanage;

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by MyEclipse Persistence Tools
 */

public class Role implements java.io.Serializable {

	// Fields

	private Long roleid;

	private String rolename;

	private String memo;
	
	private String roletype;

	private Set UserRoles = new HashSet(0);

	private Set TRoleFuncs = new HashSet(0);

	private Set TRoleLevels = new HashSet(0);
	
	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(Long roleid) {
		this.roleid = roleid;
	}

	/** full constructor */
	public Role(Long roleid, String rolename, String memo, Set TUserRoles,
			Set TRoleFuncs) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.memo = memo;
		this.UserRoles = TUserRoles;
		this.TRoleFuncs = TRoleFuncs;
	}

	// Property accessors

	public Long getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Long roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTRoleFuncs() {
		return this.TRoleFuncs;
	}

	public void setTRoleFuncs(Set TRoleFuncs) {
		this.TRoleFuncs = TRoleFuncs;
	}

	public Set getUserRoles() {
		return UserRoles;
	}

	public void setUserRoles(Set userRoles) {
		UserRoles = userRoles;
	}

	public String getRoletype() {
		return roletype;
	}

	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}

	public Set getTRoleLevels() {
		return TRoleLevels;
	}

	public void setTRoleLevels(Set roleLevels) {
		TRoleLevels = roleLevels;
	}

}