package com.funtalk.pojo.rightmanage;

/**
 * RoleLevel generated by MyEclipse Persistence Tools
 */

public class RoleLevel implements java.io.Serializable {

	// Fields

	private RoleLevelId id;
	
	private Role TRole;

	// Constructors

	/** default constructor */
	public RoleLevel() {
	}

	/** full constructor */
	public RoleLevel(RoleLevelId id) {
		this.id = id;
	}

	// Property accessors

	public RoleLevelId getId() {
		return this.id;
	}

	public void setId(RoleLevelId id) {
		this.id = id;
	}

	public Role getTRole() {
		return TRole;
	}

	public void setTRole(Role role) {
		TRole = role;
	}

}