package com.funtalk.pojo.rightmanage;

/**
 * UserRole generated by MyEclipse Persistence Tools
 */

public class UserRole implements java.io.Serializable {

	// Fields

	private UserRoleId id;

	private Role TRole;

	private User TUser;

	// Constructors

	/** default constructor */
	public UserRole() {
	}

	/** minimal constructor */
	public UserRole(UserRoleId id, Role TRole) {
		this.id = id;
		this.TRole = TRole;
	}

	/** full constructor */
	public UserRole(UserRoleId id, Role TRole, User TUser) {
		this.id = id;
		this.TRole = TRole;
		this.TUser = TUser;
	}

	// Property accessors

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	public Role getTRole() {
		return this.TRole;
	}

	public void setTRole(Role TRole) {
		this.TRole = TRole;
	}

	public User getTUser() {
		return this.TUser;
	}

	public void setTUser(User TUser) {
		this.TUser = TUser;
	}

}