package com.funtalk.pojo.rightmanage;

import java.util.Date;

/**
 * UserPwdHistoryId generated by MyEclipse Persistence Tools
 */

public class UserPwdHistoryId implements java.io.Serializable {

	// Fields

	private User TUser;

	private String pwd;

	private Date modifyDate;

	// Constructors

	/** default constructor */
	public UserPwdHistoryId() {
	}

	/** full constructor */
	public UserPwdHistoryId(User TUser, String pwd, Date modifyDate) {
		this.TUser = TUser;
		this.pwd = pwd;
		this.modifyDate = modifyDate;
	}

	// Property accessors

	public User getTUser() {
		return this.TUser;
	}

	public void setTUser(User TUser) {
		this.TUser = TUser;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserPwdHistoryId))
			return false;
		UserPwdHistoryId castOther = (UserPwdHistoryId) other;

		return ((this.getTUser() == castOther.getTUser()) || (this.getTUser() != null
				&& castOther.getTUser() != null && this.getTUser().equals(
				castOther.getTUser())))
				&& ((this.getPwd() == castOther.getPwd()) || (this.getPwd() != null
						&& castOther.getPwd() != null && this.getPwd().equals(
						castOther.getPwd())))
				&& ((this.getModifyDate() == castOther.getModifyDate()) || (this
						.getModifyDate() != null
						&& castOther.getModifyDate() != null && this
						.getModifyDate().equals(castOther.getModifyDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTUser() == null ? 0 : this.getTUser().hashCode());
		result = 37 * result
				+ (getPwd() == null ? 0 : this.getPwd().hashCode());
		result = 37
				* result
				+ (getModifyDate() == null ? 0 : this.getModifyDate()
						.hashCode());
		return result;
	}

}