package com.funtalk.pojo.rightmanage;

/**
 * UserRoleId generated by MyEclipse Persistence Tools
 */

public class UserRoleId implements java.io.Serializable {

	// Fields

	private Role TRole;

	private User TUser;

	// Constructors

	/** default constructor */
	public UserRoleId() {
	}

	/** minimal constructor */
	public UserRoleId(Role TRole) {
		this.TRole = TRole;
	}

	/** full constructor */
	public UserRoleId(Role TRole, User TUser) {
		this.TRole = TRole;
		this.TUser = TUser;
	}

	// Property accessors

	public Role getTRole() {
		return this.TRole;
	}

	public void setTRole(Role TRole) {
		this.TRole = TRole;
	}

	public User getTUser() {
		return this.TUser;
	}

	public void setTUser(User TUser) {
		this.TUser = TUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return ((this.getTRole() == castOther.getTRole()) || (this.getTRole() != null
				&& castOther.getTRole() != null && this.getTRole().equals(
				castOther.getTRole())))
				&& ((this.getTUser() == castOther.getTUser()) || (this
						.getTUser() != null
						&& castOther.getTUser() != null && this.getTUser()
						.equals(castOther.getTUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTRole() == null ? 0 : this.getTRole().hashCode());
		result = 37 * result
				+ (getTUser() == null ? 0 : this.getTUser().hashCode());
		return result;
	}

}