package com.funtalk.pojo.rightmanage;

/**
 * UserPwdHistory generated by MyEclipse Persistence Tools
 */

public class UserPwdHistory implements java.io.Serializable {

	// Fields

	private UserPwdHistoryId id;

	private User TUser;

	// Constructors

	/** default constructor */
	public UserPwdHistory() {
	}

	/** minimal constructor */
	public UserPwdHistory(UserPwdHistoryId id) {
		this.id = id;
	}

	/** full constructor */
	public UserPwdHistory(UserPwdHistoryId id, User TUser) {
		this.id = id;
		this.TUser = TUser;
	}

	// Property accessors

	public UserPwdHistoryId getId() {
		return this.id;
	}

	public void setId(UserPwdHistoryId id) {
		this.id = id;
	}

	public User getTUser() {
		return this.TUser;
	}

	public void setTUser(User TUser) {
		this.TUser = TUser;
	}

}